package model.eo;

import model.eo.common.AppModule;

import model.vo.DepartmentsViewImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 23 15:42:57 ART 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public DepartmentsViewImpl getDepartmentsView1() {
        return (DepartmentsViewImpl) findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for DepartmentsViewManager200.
     * @return DepartmentsViewManager200
     */
    public DepartmentsViewImpl getDepartmentsViewManager200() {
        return (DepartmentsViewImpl) findViewObject("DepartmentsViewManager200");
    }

    /**
     * Container's getter for DepartmentsViewManager100.
     * @return DepartmentsViewManager100
     */
    public DepartmentsViewImpl getDepartmentsViewManager100() {
        return (DepartmentsViewImpl) findViewObject("DepartmentsViewManager100");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl) findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for DeptEmployeesViewLink1.
     * @return DeptEmployeesViewLink1
     */
    public ViewLinkImpl getDeptEmployeesViewLink1() {
        return (ViewLinkImpl) findViewLink("DeptEmployeesViewLink1");
    }
    
    public boolean createNewDeptFromAM(){
        try{
            Row deptRow = getDepartmentsView1().createRow();
            deptRow.setAttribute("DepartmentId",502);
            deptRow.setAttribute("DepartmentName","New dept from AM");
            deptRow.setAttribute("ManagerId",100);
            getDepartmentsView1().insertRow(deptRow);
            return true;
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return false;
    }

    @Override
    public void afterCommit(TransactionEvent transactionEvent) {
        // TODO Implement this method
        super.afterCommit(transactionEvent);
        System.out.println("Commit operation is done");
    }

    @Override
    public void afterRollback(TransactionEvent transactionEvent) {
        
        super.afterRollback(transactionEvent);
        System.out.println("Rollback operation is done");
    }
}

