package model.eo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 23 15:57:20 ART 2022
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    boolean createNewDeptFromAM();
}

